### ISSUE TITLE
EOFException still happening.

### ISSUE THREAD

**Issue by Sp00kableDev** [PlaceholderAPI/Bungeecord-Expansion#11]
Papi dump:
`Generated: April 25, 2023 at 10:02:18 AM UTC

PlaceholderAPI: 2.11.3

Expansions Registered:
  FateHub   [Author: [BGHDDevelopmentLLC], Version: 2.2.18]
  bungee    [Author: clip, Version: 2.3]
  luckperms [Author: Luck, Version: 5.4-R2]
  player    [Author: clip, Version: 2.0.4]
  spark     [Author: Luck, Version: 1.10.37]

Expansions Directory:
  Expansion-luckperms.jar
  Expansion-Bungee.jar
  Expansion-player.jar

Server Info: 1.19.4-R0.1-SNAPSHOT/git-Purpur-1956 (MC: 1.19.4)
Java Version: 17.0.1

Plugin Info:
  BisectHosting   [Version: 1.0.4]
  BungeeGuard     [Version: 1.3-SNAPSHOT]
  FateHubCore     [Version: 2.2.18]
  LuckPerms       [Version: 5.4.71]
  Pl-Hide-Pro     [Version: 2.6.10]
  PlaceholderAPI  [Version: 2.11.3]
  ProtocolLib     [Version: 5.0.0-SNAPSHOT-b630]
  TAB             [Version: 3.3.2]
  TaggerNationLib [Version: 0.1]
  Vault           [Version: 1.7.3-b131]
  ViaBackwards    [Version: 4.6.1]
  ViaVersion      [Version: 4.6.2]
  WorldEdit       [Version: 7.2.14+6360-094b734]
  spark           [Version: 1.10.37]`

Still recieving the following error in console:
`[25.04 16:04:06] [Server] [WARN] [PlaceholderAPI] Plugin PlaceholderAPI v2.11.3 generated an exception whilst handling plugin message
[25.04 16:04:06] [Server] java.lang.IllegalStateExceptionjava.io.EOFException
[25.04 16:04:06] [Server] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:472) ~[guava-31.1-jre.jar:?]
[25.04 16:04:06] [Server] 	at com.extendedclip.papi.bungeeexpansion.BungeeExpansion.onPluginMessageReceived(BungeeExpansion.java:124) ~[?:?]
[25.04 16:04:06] [Server] 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
[25.04 16:04:06] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3698) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1956]
[25.04 16:04:06] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[25.04 16:04:06] [Server] Caused byjava.io.EOFException
[25.04 16:04:06] [Server] 	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:346) ~[?:?]
[25.04 16:04:06] [Server] 	at java.io.DataInputStream.readUTF(DataInputStream.java:595) ~[?:?]
[25.04 16:04:06] [Server] 	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
[25.04 16:04:06] [Server] 	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:470) ~[guava-31.1-jre.jar:?]
[25.04 16:04:06] [Server] 	... more`
  
I did try the EOFException branch, unfortunately to no avail. Hoping to see a new commit soon. :))

**Comment by Splitrox** [comment]
bump

**Comment by NovaPixell** [comment]
Same issue here!
