### ISSUE TITLE
Error getting value of variable

### ISSUE THREAD

**Issue by 157946a** [PlaceholderAPI/Bungeecord-Expansion#6]
[14:18:38 WARN]: [PlaceholderAPI] Task #1704 for PlaceholderAPI v2.10.10 generated an exception
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:482) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1128) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.getServers(BungeeCordExpansion.java:108) ~[?:?]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.access$100(BungeeCordExpansion.java:45) ~[?:?]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion$1.run(BungeeCordExpansion.java:201) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:829) [?:?]

In the same version of other sub-servers, there is no error, but there was an accident in my BadWars, and it was used on trhologram, papi parse did not have this situation, and other sub-services took %bungee_BadWars% and it was fine. It happened in the sub-server BadWars. By the way, can I add a check to see if the server is turned on and display different content?

**Comment by BlitzOffline** [comment]
This is related to you having 2 or more copies of the BungeeExpansion installed. Go to plugins/PlaceholderAPI/expansions, remove all copies of the expansion, do a /papi reload, redownload using /papi ecloud download bungee then another /papi reload.
